// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Post = Collections['allPosts']['schema']['_output']
export declare const allPosts: Post[]

export type Project = Collections['allProjects']['schema']['_output']
export declare const allProjects: Project[]

export type Page = Collections['allPages']['schema']['_output']
export declare const allPages: Page[]
