// This file is generated by Velite

export { default as allPosts } from './allPosts.json'
export { default as allProjects } from './allProjects.json'
export { default as allPages } from './allPages.json'